# Generated by carnix 0.9.2: carnix generate-nix --src . --standalone
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
let cratesIO = callPackage ./crates-io.nix { };
    crates = cratesIO // rec {
# hex-string-0.1.0

  crates.hex_string."0.1.0" = deps: { features?(features_.hex_string."0.1.0" deps {}) }: buildRustCrate {
    crateName = "hex-string";
    version = "0.1.0";
    authors = [ "Savanni D'Gerinel <savanni@luminescent-dreams.com>" ];
    src = exclude [ ".git" "target" ] ./.;
  };
  features_.hex_string."0.1.0" = deps: f: updateFeatures f (rec {
    hex_string."0.1.0".default = (f.hex_string."0.1.0".default or true);
  }) [];


# end

}; in

rec {
  hex_string = crates.crates.hex_string."0.1.0" deps;
  __all = [ (hex_string {}) ];
  deps.hex_string."0.1.0" = {};
}
